version: '2.1'
services: 
  app:
    build: .
    ports: 
      - '19003:19003'
    depends_on: 
      - mongodb

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sistema
      MONGO_INITDB_ROOT_PASSWORD: lucas322